# FROM debian or alpina - most optimized
# i.e. FROM debian

# ENV
# i.e. ENV Name World

# COPY  adds files from your Docker client's current dir
# i.e. COPY . /app

# RUN 
# i.e. RUN make /app

# CMD specifies what command to run in the container
# i.e CMD python /app/app.py
