# FROM debian or alpina - most optimized
# FROM debian

# COPY  adds files from your Docker client's current dir
# COPY . /app

# RUN 
# RUN make /app
# CMD specifies what command to run in the container
# CMD python /app/app.py
